// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import LogoSvg from "./logo.svg";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

import './App.css';
;

var logo = LogoSvg;

var initialState_todoList = [];

var initialState = {
  todoList: initialState_todoList,
  inputValue: ""
};

function reducer(state, action) {
  if (typeof action === "number") {
    if (action === /* AddTodo */0) {
      return {
              todoList: state.todoList.concat([{
                      title: state.inputValue,
                      isDone: false
                    }]),
              inputValue: ""
            };
    } else {
      return {
              todoList: [],
              inputValue: state.inputValue
            };
    }
  }
  if (action.TAG === /* InputChanged */0) {
    return {
            todoList: state.todoList,
            inputValue: action._0
          };
  }
  var idx = action._0;
  return {
          todoList: Belt_Array.mapWithIndex(state.todoList, (function (id, ele) {
                  if (id === idx) {
                    return {
                            title: ele.title,
                            isDone: !ele.isDone
                          };
                  } else {
                    return ele;
                  }
                })),
          inputValue: state.inputValue
        };
}

function App(Props) {
  var match = React.useReducer(reducer, initialState);
  var dispatch = match[1];
  var state = match[0];
  var handleInput = function (e) {
    var inputVal = e.target.value;
    return Curry._1(dispatch, {
                TAG: /* InputChanged */0,
                _0: inputVal
              });
  };
  var handleAdd = function (param) {
    return Curry._1(dispatch, /* AddTodo */0);
  };
  var handleRemove = function (param) {
    return Curry._1(dispatch, /* ClearTodos */1);
  };
  return React.createElement("div", {
              className: "App"
            }, React.createElement("h1", undefined, "TODO"), React.createElement("input", {
                  type: "text",
                  value: state.inputValue,
                  onChange: handleInput
                }), React.createElement("button", {
                  onClick: handleAdd
                }, "Add Todo"), React.createElement("button", {
                  onClick: handleRemove
                }, "Clear all Todo"), Belt_Array.mapWithIndex(state.todoList, (function (idx, ele) {
                    return React.createElement("div", {
                                key: ele.title,
                                style: {
                                  background: ele.isDone ? "green" : "steelblue",
                                  color: "white",
                                  fontSize: "1.5rem",
                                  margin: "1rem 0",
                                  padding: "1 rem",
                                  textDecoration: ele.isDone ? "line-through" : "intial"
                                },
                                onClick: (function (param) {
                                    return Curry._1(dispatch, {
                                                TAG: /* MarkDone */1,
                                                _0: idx
                                              });
                                  })
                              }, ele.title);
                  })));
}

var make = App;

export {
  logo ,
  initialState ,
  reducer ,
  make ,
  
}
/*  Not a pure module */
